site_name = "Le Journal de Writober d'Ewjoachim"
description = "Une nouvelle par jour d'octobre sur le thème du mot du jour d'Inktober"
copyright = "2024- Joachim Jablon - CC-BY-SA-NC"
author = "Joachim Jablon"
locale = "fr-fr"
timezone = "Europe/Paris"
server_url = "https://writober.ewjoach.im"
repository_url = "https://github.com/ewjoachim/writober"
colors = [
    "#dd3300",
    "#f46101",
    "#f9980d",
    "#f4ca26",
    "#c0de48",
    "#77e173",
    "#31c8a7",
    "#de3e02",
    "#f47504",
    "#fdad16",
    "#fddc41",
    "#dbf172",
    "#9df1a3",
    "#4bcac3",
    "#da340c",
    "#f36710",
    "#fba921",
    "#f9df4c",
    "#c4f383",
    "#82f1af",
    "#3ac5c8",
    "#ce2619",
    "#f24d17",
    "#f88220",
    "#f9be4a",
    "#b4be9b",
    "#62ccc0",
    "#29abcd",
    "#bf1424",
    "#e22014",
    "#e84a31",
    "#e47178",
    "#9d69bb",
    "#4b73d5",
    "#156bce",
    "#901653",
    "#ae183e",
    "#b02b56",
    "#ad4084",
    "#773fae",
    "#3d40c1",
    "#153db7",
]
index_colors = ["#fdad16", "#9df1a3", "#3ac5c8", "#773fae", "#ae183e"]
logo = "android-chrome-512x512.png"
title_ttf_font = "Quicksand"
body_ttf_font = "Bitter"

[[icon_links]]
rel = "icon"
type = "image/png"
sizes = "32x32"
href = "favicon-32x32.png"

[[icon_links]]
rel = "icon"
type = "image/png"
sizes = "16x16"
href = "favicon-16x16.png"

[[icon_links]]
rel = "apple-touch-icon"
sizes = "180x180"
href = "apple-touch-icon.png"

[[icon_links]]
rel = "manifest"
href = "site.webmanifest"

[cms_config.backend]
repo = "ewjoachim/writober"
name = "github"
